### ISSUE TITLE
Bridge 'device IDs'

### ISSUE THREAD

**Issue by takluyver** [European-XFEL/euxfel-python#21]
Karabo devices are identified with a 3-part name like `SPB_XTD9_XGM/DOOCS/MAIN`. However, some of the device IDs stored in the HDF5 files (the ones for INSTRUMENT data) have a suffix, like `SPB_XTD9_XGM/DOOCS/MAIN:output/data`.

- `H5File.devices` is a list of the IDs as stored in the file, i.e. including the suffix.
- The code to select data by device splits the stored ID on slashes and rejoins the first three parts, so we would get `SPB_XTD9_XGM/DOOCS/MAIN:output` as the device name, which isn't quite the same as either.

We should rationalise what kind of device IDs the interface works with. Bearing in mind that the file format may change, I suspect it makes sense to work with the Karabo names. But I'm not sure what to do with the suffix. Should it be part of the key within the deivce, e.g. `output.data.intensityTD`? We also need to ensure the returned data dict matches what karabo bridge gives.

**Comment by tmichela** [comment]
Tough question :)

On one side, it make sens to differentiate a single device's data sources according to input source (input channel or message broker), i.e
`SPB_XTD9_XGM/DOOCS/MAIN`
`SPB_XTD9_XGM/DOOCS/MAIN:output`
`SPB_XTD9_XGM/DOOCS/MAIN:output2`
...

These can be considered as different data sources (or devices) even if the original source is the same unique device `SPB_XTD9_XGM/DOOCS/MAIN`. As it give information on the data interface.
It also kind of reflects what happens in the Karabo world as:
1. pipeline data would come in a Karabo `Hash` container where neither device name not interface name is mentioned i.e. `Hash('key.subkey', value)` but associated with a `metadata` object containing source information (typically `DEVICE_NAME/IN_THREE_PARTS:output_channel_name` and a `timestamp`).
2. `slow data` comes (to be confirmed) as a karabo `Hash` containing the (full or partial) device configuration, so you would access the data by `hash.get('key.subkey')`.

On the other side, the output channels are part of the device configuration so it would also make sense to have it as a property key name, i.e. `deviceHash.get('output.schema.data.image')`.
Then one single device exists, regarding the data source.

I would prefer the first approach as it reflects best the Karabo architecture. But this is important enough to involve more people in the discussion.

**Comment by takluyver** [comment]
Thanks. Who else should we ask about it? Hans?

**Comment by takluyver** [comment]
We agreed to use the form that includes the output channel (for instrument devices), but excludes the first level key which the files treat as part of the name. So the package will work with device names like `"FXE_DET_LPD1M-1/DET/15CH0:xtdf"` .

For control devices, there is no disagreement - everything uses device names like `"SA3_XTD10_VAC/TSENS/S30100K"` .
